services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  postino:
    build:
      context: .
      dockerfile: src/Tero.Postino.Api/Dockerfile
      secrets:
        - packages_user
        - packages_token
    depends_on:
      - rabbitmq
    environment:
      - Rabbit__Host=rabbitmq
      - Rabbit__User=guest
      - Rabbit__Password=guest
      - Smtp__Enabled=false
      - MailJournal__BasePath=/mails
    volumes:
      - postino-mails:/mails
    ports:
      - '8081:80'

volumes:
  rabbitmq-data:
  postino-mails:

secrets:
  packages_user:
    environment: GITHUB_PACKAGES_USER
  packages_token:
    environment: GITHUB_PACKAGES_TOKEN
