<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
	<ProjectReference Include="..\Tero.Postino.Domain\Tero.Postino.Domain.csproj" />
	<ProjectReference Include="..\..\..\..\shared\Tero.Contracts\Tero.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Ports\" />
	</ItemGroup>
</Project>
